"""create rag evaluations table

Revision ID: 0682ad38c5ac
Revises: 92131af92e29
Create Date: 2026-07-22 10:09:25.407883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0682ad38c5ac'
down_revision: Union[str, Sequence[str], None] = '92131af92e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('grounded', sa.Boolean(), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('retrieval_relevance', sa.Float(), nullable=False),
    sa.Column('citation_coverage', sa.Float(), nullable=False),
    sa.Column('groundedness_consistency', sa.Float(), nullable=False),
    sa.Column('response_latency_ms', sa.Float(), nullable=False),
    sa.Column('retrieved_candidate_count', sa.Integer(), nullable=False),
    sa.Column('relevant_candidate_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('citation_count >= 0', name='ck_rag_evaluations_citation_count'),
    sa.CheckConstraint('citation_coverage >= 0 AND citation_coverage <= 1', name='ck_rag_evaluations_citation_coverage'),
    sa.CheckConstraint('groundedness_consistency >= 0 AND groundedness_consistency <= 1', name='ck_rag_evaluations_groundedness_consistency'),
    sa.CheckConstraint('relevant_candidate_count >= 0', name='ck_rag_evaluations_relevant_count'),
    sa.CheckConstraint('response_latency_ms >= 0', name='ck_rag_evaluations_response_latency'),
    sa.CheckConstraint('retrieval_relevance >= 0 AND retrieval_relevance <= 1', name='ck_rag_evaluations_retrieval_relevance'),
    sa.CheckConstraint('retrieved_candidate_count >= 0', name='ck_rag_evaluations_retrieved_count'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rag_evaluations_organization_created_at', 'rag_evaluations', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_rag_evaluations_organization_grounded', 'rag_evaluations', ['organization_id', 'grounded'], unique=False)
    op.create_index(op.f('ix_rag_evaluations_organization_id'), 'rag_evaluations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rag_evaluations_user_id'), 'rag_evaluations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_evaluations_user_id'), table_name='rag_evaluations')
    op.drop_index(op.f('ix_rag_evaluations_organization_id'), table_name='rag_evaluations')
    op.drop_index('ix_rag_evaluations_organization_grounded', table_name='rag_evaluations')
    op.drop_index('ix_rag_evaluations_organization_created_at', table_name='rag_evaluations')
    op.drop_table('rag_evaluations')
    # ### end Alembic commands ###
